### ISSUE TITLE
This library works only with react-native 0.60+?

### ISSUE THREAD

**Issue by joaom182** [th3rdwave/react-native-safe-area-context#53]
I'm trying to use this library with my react-native project 0.59.9.

But when i initialize the `SafeAreaProvider`, throws an error:

```
React.usecontext is not a function
```

**Comment by janicduplessis** [comment]
It should work on 0.59, the error looks related to an old version of react that doesn't support hooks. Make sure you are using `react@^16.8.0`.

**Comment by joaom182** [comment]
React 16.8.0 is retrocompatible? Or I'll have issues for update?
