### ISSUE TITLE
Android compile error

### ISSUE THREAD

**Issue by JogiPrasadPakki** [th3rdwave/react-native-safe-area-context#51]
Gradle through error when gradle build

node_modules\react-native-safe-area-context\android\src\main\java\com\th3rdwave\safeareacontext\InsetsChangeEvent.java:28: error: incompatible types: ReadableMap cannot be converted to WritableMap
    event.putMap("insets", SafeAreaUtils.edgeInsetsToJsMap(mInsets));
                                                          ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

FAILURE: Build failed with an exception.

**Comment by janicduplessis** [comment]
Ok, I'm not sure why I'm not getting this error but I tried a fix. Can you check if it works with version 0.7.2?

**Comment by janicduplessis** [comment]
Going to assume its fixed and close this.
